name: 'doc'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:


  btd:
    name: '📓 Docs'
    runs-on: ubuntu-latest
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v2

    - name: '📓 BuildTheDocs (BTD)'
      uses: buildthedocs/btd@v0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        skip-deploy: github.event_name == 'pull_request'

    - name: '📤 Upload artifact: HTML'
      uses: actions/upload-artifact@master
      with:
        name: doc
        path: doc/_build/html
